//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talegen.AspNetCore.Scim.Schema.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// Class Resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        /// <summary>
        /// The resource man
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// The resource culture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Resources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <summary>
        /// Gets the resource manager.
        /// </summary>
        /// <value>The resource manager.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talegen.AspNetCore.Scim.Schema.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <summary>
        /// Gets or sets the culture.
        /// </summary>
        /// <value>The culture.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The event token has expired..
        /// </summary>
        /// <summary>
        /// Gets the exception event token expired.
        /// </summary>
        /// <value>The exception event token expired.</value>
        public static string ExceptionEventTokenExpired {
            get {
                return ResourceManager.GetString("ExceptionEventTokenExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This value is invalid for the claim, {0}: {1}..
        /// </summary>
        /// <summary>
        /// Gets the exception event token invalid claim value template.
        /// </summary>
        /// <value>The exception event token invalid claim value template.</value>
        public static string ExceptionEventTokenInvalidClaimValueTemplate {
            get {
                return ResourceManager.GetString("ExceptionEventTokenInvalidClaimValueTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The token is missing a value for this required claim: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception event token missing claim template.
        /// </summary>
        /// <value>The exception event token missing claim template.</value>
        public static string ExceptionEventTokenMissingClaimTemplate {
            get {
                return ResourceManager.GetString("ExceptionEventTokenMissingClaimTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filtering by this attribute is not supported: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception filter attribute path not supported template.
        /// </summary>
        /// <value>The exception filter attribute path not supported template.</value>
        public static string ExceptionFilterAttributePathNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionFilterAttributePathNotSupportedTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only a query with exactly one filter is supported..
        /// </summary>
        /// <summary>
        /// Gets the exception filter count.
        /// </summary>
        /// <value>The exception filter count.</value>
        public static string ExceptionFilterCount {
            get {
                return ResourceManager.GetString("ExceptionFilterCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The filter is not supported..
        /// </summary>
        /// <summary>
        /// Gets the exception filter not supported.
        /// </summary>
        /// <value>The exception filter not supported.</value>
        public static string ExceptionFilterNotSupported {
            get {
                return ResourceManager.GetString("ExceptionFilterNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This filter operator is not supported: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception filter operator not supported template.
        /// </summary>
        /// <value>The exception filter operator not supported template.</value>
        public static string ExceptionFilterOperatorNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionFilterOperatorNotSupportedTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An attribute is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid attribute.
        /// </summary>
        /// <value>The exception invalid attribute.</value>
        public static string ExceptionInvalidAttribute {
            get {
                return ResourceManager.GetString("ExceptionInvalidAttribute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A batch is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid batch.
        /// </summary>
        /// <value>The exception invalid batch.</value>
        public static string ExceptionInvalidBatch {
            get {
                return ResourceManager.GetString("ExceptionInvalidBatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The context is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid context.
        /// </summary>
        /// <value>The exception invalid context.</value>
        public static string ExceptionInvalidContext {
            get {
                return ResourceManager.GetString("ExceptionInvalidContext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This filter is invalid: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid filter template.
        /// </summary>
        /// <value>The exception invalid filter template.</value>
        public static string ExceptionInvalidFilterTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidFilterTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An identifier is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid identifier.
        /// </summary>
        /// <value>The exception invalid identifier.</value>
        public static string ExceptionInvalidIdentifier {
            get {
                return ResourceManager.GetString("ExceptionInvalidIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This identifier is invalid: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid identifier template.
        /// </summary>
        /// <value>The exception invalid identifier template.</value>
        public static string ExceptionInvalidIdentifierTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidIdentifierTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An operation is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid operation.
        /// </summary>
        /// <value>The exception invalid operation.</value>
        public static string ExceptionInvalidOperation {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The operation with this identifier is not valid: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid operation template.
        /// </summary>
        /// <value>The exception invalid operation template.</value>
        public static string ExceptionInvalidOperationTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperationTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This operator is not supported: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid operator template.
        /// </summary>
        /// <value>The exception invalid operator template.</value>
        public static string ExceptionInvalidOperatorTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperatorTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The parameters are invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid parameters.
        /// </summary>
        /// <value>The exception invalid parameters.</value>
        public static string ExceptionInvalidParameters {
            get {
                return ResourceManager.GetString("ExceptionInvalidParameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This path is invalid: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid path template.
        /// </summary>
        /// <value>The exception invalid path template.</value>
        public static string ExceptionInvalidPathTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidPathTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid request.
        /// </summary>
        /// <value>The exception invalid request.</value>
        public static string ExceptionInvalidRequest {
            get {
                return ResourceManager.GetString("ExceptionInvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid request1.
        /// </summary>
        /// <value>The exception invalid request1.</value>
        public static string ExceptionInvalidRequest1 {
            get {
                return ResourceManager.GetString("ExceptionInvalidRequest1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A resource is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid resource.
        /// </summary>
        /// <value>The exception invalid resource.</value>
        public static string ExceptionInvalidResource {
            get {
                return ResourceManager.GetString("ExceptionInvalidResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The resource is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid resource1.
        /// </summary>
        /// <value>The exception invalid resource1.</value>
        public static string ExceptionInvalidResource1 {
            get {
                return ResourceManager.GetString("ExceptionInvalidResource1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The response is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid response.
        /// </summary>
        /// <value>The exception invalid response.</value>
        public static string ExceptionInvalidResponse {
            get {
                return ResourceManager.GetString("ExceptionInvalidResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This count value is invalid: {0}.  A non-negative number is expected..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid search request count template.
        /// </summary>
        /// <value>The exception invalid search request count template.</value>
        public static string ExceptionInvalidSearchRequestCountTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidSearchRequestCountTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This sort order value is invalid: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid sort order template.
        /// </summary>
        /// <value>The exception invalid sort order template.</value>
        public static string ExceptionInvalidSortOrderTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidSortOrderTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This start index value is invalid: {0}.  The start index is a 1-based index..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid start index template.
        /// </summary>
        /// <value>The exception invalid start index template.</value>
        public static string ExceptionInvalidStartIndexTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidStartIndexTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The state is invalid..
        /// </summary>
        /// <summary>
        /// Gets the state of the exception invalid.
        /// </summary>
        /// <value>The state of the exception invalid.</value>
        public static string ExceptionInvalidState {
            get {
                return ResourceManager.GetString("ExceptionInvalidState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested state transition is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid state transition.
        /// </summary>
        /// <value>The exception invalid state transition.</value>
        public static string ExceptionInvalidStateTransition {
            get {
                return ResourceManager.GetString("ExceptionInvalidStateTransition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A value is invalid..
        /// </summary>
        /// <summary>
        /// Gets the exception invalid value.
        /// </summary>
        /// <value>The exception invalid value.</value>
        public static string ExceptionInvalidValue {
            get {
                return ResourceManager.GetString("ExceptionInvalidValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This method is not supported: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception method not supported template.
        /// </summary>
        /// <value>The exception method not supported template.</value>
        public static string ExceptionMethodNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionMethodNotSupportedTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This type of resource can only have one resource type schema identifier: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception multiple qualified resource type identifiers template.
        /// </summary>
        /// <value>The exception multiple qualified resource type identifiers template.</value>
        public static string ExceptionMultipleQualifiedResourceTypeIdentifiersTemplate {
            get {
                return ResourceManager.GetString("ExceptionMultipleQualifiedResourceTypeIdentifiersTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The monitoring behavior has not been properly initialized..
        /// </summary>
        /// <summary>
        /// Gets the exception not initialized monitoring behavior.
        /// </summary>
        /// <value>The exception not initialized monitoring behavior.</value>
        public static string ExceptionNotInitializedMonitoringBehavior {
            get {
                return ResourceManager.GetString("ExceptionNotInitializedMonitoringBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The provider behavior has not been properly initialized..
        /// </summary>
        /// <summary>
        /// Gets the exception not initialized provider behavior.
        /// </summary>
        /// <value>The exception not initialized provider behavior.</value>
        public static string ExceptionNotInitializedProviderBehavior {
            get {
                return ResourceManager.GetString("ExceptionNotInitializedProviderBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pagination is not supported for this type of resource: {0}.
        /// </summary>
        /// <summary>
        /// Gets the exception pagination is not supported template.
        /// </summary>
        /// <value>The exception pagination is not supported template.</value>
        public static string ExceptionPaginationIsNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionPaginationIsNotSupportedTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A value greater than zero is required for this argument: {0}..
        /// </summary>
        /// <summary>
        /// Gets the exception postive integer range template.
        /// </summary>
        /// <value>The exception postive integer range template.</value>
        public static string ExceptionPostiveIntegerRangeTemplate {
            get {
                return ResourceManager.GetString("ExceptionPostiveIntegerRangeTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The query is not supported..
        /// </summary>
        /// <summary>
        /// Gets the exception query not supported.
        /// </summary>
        /// <value>The exception query not supported.</value>
        public static string ExceptionQueryNotSupported {
            get {
                return ResourceManager.GetString("ExceptionQueryNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The following cannot be assigned to the &quot;value&quot; attribute of an Azure Active Directory role: {0}.  It exceeds the maximum permissible length for that attribute, which is this many characters: {1}..
        /// </summary>
        /// <summary>
        /// Gets the exception role value length exceeded template.
        /// </summary>
        /// <value>The exception role value length exceeded template.</value>
        public static string ExceptionRoleValueLengthExceededTemplate {
            get {
                return ResourceManager.GetString("ExceptionRoleValueLengthExceededTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only a single event was expected..
        /// </summary>
        /// <summary>
        /// Gets the exception single event expected.
        /// </summary>
        /// <value>The exception single event expected.</value>
        public static string ExceptionSingleEventExpected {
            get {
                return ResourceManager.GetString("ExceptionSingleEventExpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A bulk operation must have a unique identifier..
        /// </summary>
        /// <summary>
        /// Gets the exception unidentifiable operation.
        /// </summary>
        /// <value>The exception unidentifiable operation.</value>
        public static string ExceptionUnidentifiableOperation {
            get {
                return ResourceManager.GetString("ExceptionUnidentifiableOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The schema could not be identified..
        /// </summary>
        /// <summary>
        /// Gets the exception unidentifiable schema.
        /// </summary>
        /// <value>The exception unidentifiable schema.</value>
        public static string ExceptionUnidentifiableSchema {
            get {
                return ResourceManager.GetString("ExceptionUnidentifiableSchema", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An authentication scheme must have a name..
        /// </summary>
        /// <summary>
        /// Gets the exception unnamed authentication scheme.
        /// </summary>
        /// <value>The exception unnamed authentication scheme.</value>
        public static string ExceptionUnnamedAuthenticationScheme {
            get {
                return ResourceManager.GetString("ExceptionUnnamedAuthenticationScheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        /// <summary>
        /// Gets the header template.
        /// </summary>
        /// <value>The header template.</value>
        public static string HeaderTemplate {
            get {
                return ResourceManager.GetString("HeaderTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data has been read..
        /// </summary>
        /// <summary>
        /// Gets the information read.
        /// </summary>
        /// <value>The information read.</value>
        public static string InformationRead {
            get {
                return ResourceManager.GetString("InformationRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing of this request was completed: {0}.  
        ///
        ///The status code of the response was {1}.
        /// </summary>
        /// <summary>
        /// Gets the information request processed template.
        /// </summary>
        /// <value>The information request processed template.</value>
        public static string InformationRequestProcessedTemplate {
            get {
                return ResourceManager.GetString("InformationRequestProcessedTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to This request was received: {0}..
        /// </summary>
        /// <value>The information request received template.</value>
        public static string InformationRequestReceivedTemplate {
            get {
                return ResourceManager.GetString("InformationRequestReceivedTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Data has been written..
        /// </summary>
        /// <value>The information wrote.</value>
        public static string InformationWrote {
            get {
                return ResourceManager.GetString("InformationWrote", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to {0} {1}
        /// {2}.
        /// </summary>
        /// <value>The message template.</value>
        public static string MessageTemplate {
            get {
                return ResourceManager.GetString("MessageTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to {0}@.
        /// </summary>
        /// <value>The monitor correlation identifier prefix template.</value>
        public static string MonitorCorrelationIdentifierPrefixTemplate {
            get {
                return ResourceManager.GetString("MonitorCorrelationIdentifierPrefixTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to {0}: {1} (Critical? {2}).
        /// </summary>
        /// <value>The monitor output exception template.</value>
        public static string MonitorOutputExceptionTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputExceptionTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to {0}: {1} (Verbose? {2}).
        /// </summary>
        /// <value>The monitor output information template.</value>
        public static string MonitorOutputInformationTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputInformationTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to {0}: {1}.
        /// </summary>
        /// <value>The monitor output template.</value>
        public static string MonitorOutputTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to {0}/{1}..
        /// </summary>
        /// <value>The resource identifier template.</value>
        public static string ResourceIdentifierTemplate {
            get {
                return ResourceManager.GetString("ResourceIdentifierTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Resource {0} not found..
        /// </summary>
        /// <value>The resource not found template.</value>
        public static string ResourceNotFoundTemplate {
            get {
                return ResourceManager.GetString("ResourceNotFoundTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ,.
        /// </summary>
        /// <value>The separator header values.</value>
        public static string SeparatorHeaderValues {
            get {
                return ResourceManager.GetString("SeparatorHeaderValues", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The supplied watermark did not match the expected watermark:
        /// Supplied:
        /// {0}
        /// Received:
        /// {1}.
        /// </summary>
        /// <value>The warning unexpected watermark template.</value>
        public static string WarningUnexpectedWatermarkTemplate {
            get {
                return ResourceManager.GetString("WarningUnexpectedWatermarkTemplate", resourceCulture);
            }
        }
    }
}
